Added explicit steps for configuring and using custom rules.
konveyor/kai pull request #276
Opened 2024-08-03 20:57 UTC by Myrausman

Fixes #212

2024-08-05 17:19 UTC, jwmatthews requested changes
Thank you for the contribution.

Please consider the comments I added to help improve the documentation and clear up confusion with the 2 places we run analysis.

2024-08-05 17:19 UTC, jwmatthews commented on docs/customApps.md
> +2. Ignore Default Rules: The analysis script is set to ignore default Kantra rules. You can review or adjust this in example/analyze.sh if needed.
Calling this out make sense, let's expand to include the 2 places that we perform analysis so folks are aware.

Note that we have 2 different places that perform analysis and currently only one of them is set to ignore the default Kantra rules.

I believe the intent of this document has focused on the analysis of sample data

1) Analysis of the 'sample data', this is analysis that runs on several sample applications where have initial/solved states.  This analysis is done to simulate what integration will look like when we run with a Konveyor instance that an organization has populated with data.   For this specific use-case we are running the below to analyze the sample apps:

https://github.com/konveyor/kai/blob/main/samples/analyze_apps.py#L83
`cmd = f'time ./bin/kantra analyze -i {source_dir} -t "quarkus" -t "jakarta-ee" -t "jakarta-ee8+" -t "jakarta-ee9+" -t "cloud-readiness" --rules {os.path.dirname(__file__)}/custom_rules -o {full_output_dir} --overwrite'`

In the above, we are allowing Kantra to use the default rules and we supplement with the custom rules.

2) We also have another place we run analysis, client side
This client side usage could be from the example/run_demo.py or from running in IDE.
Currently we are ignoring the default rules for the client side with example/run_demo.py and we experimented with a few small tweaks.

https://github.com/konveyor/kai/blob/main/example/analyze.sh#L50
`time "${KANTRA_BIN}" analyze -i "${PWD}"/"${SOURCE_DIR}" "${SOURCE_ONLY}" --enable-default-rulesets=false -t "quarkus" -t "jakarta-ee" -t "jakarta-ee8" -t "jakarta-ee9" -t "cloud-readiness" --rules "${DEFAULT_RULES_DIR}" --rules "${CUSTOM_RULES_DIR}" -o "${OUTDIR}" --overwrite`

We use the `--enable-default-rulesets=false` option client side and then pass in the below directory to use:
https://github.com/konveyor/kai/tree/main/example/default_rules

2024-08-05 18:24 UTC, Myrausman commented
@jwmatthews , Can you please confirm if this is the content you meant to include in the document?

2024-08-07 13:32 UTC, jwmatthews commented on docs/customApps.md
> +2. Ignore Default Rules: The analysis script is set to ignore default Kantra rules. You can review or adjust this in example/analyze.sh if needed.
@Myrausman this information you have is not technically correct, as the section you are documenting will NOT ignore default rules.  That is why I gave you more context so you could fully understand the 2 places we run analysis.

The documentation for this section:
https://github.com/konveyor/kai/blob/1ed90050c210c5a3597b0ef1a073eb41f4843008/docs/customApps.md#run-analysis

Is talking about how to run the analysis for the sample data which Kai will consult. 
That analysis DOES NOT ignore default rules.

Please remove:
`2. Ignore Default Rules: The analysis script is set to ignore default Kantra rules. You can review or adjust this in example/analyze.sh if needed.`

2024-08-07 13:33 UTC, jwmatthews commented on docs/customApps.md
> +<b>Note: </b> There are two different places where analysis is performed and currently only one of them is set to ignore the default Kantra rules:
Let's relocate this chunk of extra contextual information at the end of the document so we do not confuse folks.

2024-08-09 13:17 UTC, jwmatthews approved these changes
LGTM

2024-08-09 13:19 UTC, jwmatthews requested changes
Almost ready, but need to adjust a `trunk fmt` issue

Please see https://github.com/konveyor/kai/blob/main/CONTRIBUTING.md#linting for how to install/run trunk to fix this.

2024-08-10 14:15 UTC, jwmatthews approved these changes

2024-08-10 14:15 UTC, merged