fix: Fix Path Resolution in process_log_dir_replacements Function
konveyor/kai pull request #279
Opened 2024-08-05 08:27 UTC by brf153

## Summary
This PR closes #278. It addresses an issue with the `process_log_dir_replacements` function, which is responsible for replacing the $pwd placeholder in log directory paths with the path to the Kai project directory. The original function returned paths with redundant components and did not correctly resolve relative paths.

## Issue
The original function produced paths with incorrect or redundant components, such as /home/k8smaster/Desktop/kai/kai/..//logs, leading to errors and misconfiguration in the log directory paths.

## Changes Made
Function Update: Updated the process_log_dir_replacements function to:
Replace $pwd with the path to the Kai project directory, one level up from the current working directory.
Normalize the resulting path to remove redundant components and resolve relative path issues.
```
def process_log_dir_replacements(log_dir: str) -> str:
    ##
    # We want to replace $pwd with the location of the Kai project directory,
    # this is needed to help with specifying from configuration
    ##
    if log_dir.startswith("$pwd"):
        current_directory = os.getcwd()
        kai_project_directory = os.path.abspath(os.path.join(current_directory, ".."))
        log_dir = log_dir.replace("$pwd", kai_project_directory, 1)
        log_dir = os.path.normpath(log_dir)
    return log_dir
```

2024-08-05 17:26 UTC, jwmatthews commented
Thank you for your contribution.

Before we consider merging, I would like to know if you ran into functional errors that necessitated this PR or if this was more of a stylistic concern to clean up how the path was displayed.  Let's discuss in #278

2024-08-07 12:57 UTC, jwmatthews commented
@brf153 do you want to include in this PR the test you shared in 
https://github.com/konveyor/kai/issues/278#issuecomment-2269552260

2024-08-07 13:09 UTC, brf153 commented
Thank you so much, @jwmatthews ! I'm really glad the test example helped clarify things.

Regarding the test you mentioned from #278, I've actually set up a separate branch just for tests. I'd prefer to add the tests from that branch if that's alright with you. Please let me know if that works.

2024-08-07 13:18 UTC, jwmatthews commented
Works for me

2024-08-07 15:13 UTC, jwmatthews commented
We will need to make a small change before we can merge this; as of now, the log directory is being created 1 lever higher in the hierarchy than we want.

I tested this via `make run-server`, executed that while being in the kai checkout.
The log file ended up being written a level up than expected.

My kai checkout is at:
/Users/jmatthews/git/konveyor/kai

I ran `make run-server` being in: /Users/jmatthews/git/konveyor/kai
The logging file is not created under the 'konveyor/kai/logs' directory as expected, but is created at 'konveyor/logs'.

Example from console logging output:
`File logging for 'kai' is set to level 'DEBUG' writing to file: '/Users/jmatthews/git/konveyor/logs/kai_server.log'`

I also tried with something a little odder just to verify behavior.
I changed directory to /Users/jmatthews/git/konveyor
then ran:  `make -f ./kai/Makefile run-server`

Confirmed the log directory is again going a level higher in heirarchy than expected
`File logging for 'kai' is set to level 'DEBUG' writing to file: '/Users/jmatthews/git/logs/kai_server.log'`


I made the below tweak to correct this

```
$ git diff kai/kai_logging.py 
diff --git a/kai/kai_logging.py b/kai/kai_logging.py
index cc274f9..2b79d0e 100644
--- a/kai/kai_logging.py
+++ b/kai/kai_logging.py
@@ -18,7 +18,7 @@ def process_log_dir_replacements(log_dir: str) -> str:
     ##
     if log_dir.startswith("$pwd"):
         current_directory = os.getcwd()
-        kai_project_directory = os.path.abspath(os.path.join(current_directory, ".."))
+        kai_project_directory = os.path.abspath(current_directory)
         log_dir = log_dir.replace("$pwd", kai_project_directory, 1)
         log_dir = os.path.normpath(log_dir)
     return log_dir
```

Tested with podman compose to confirm logging to disk is still OK with the above tweak and looks good
`File logging for 'kai' is set to level 'DEBUG' writing to file: '/podman_compose/logs/kai_server.log'`

2024-08-07 15:15 UTC, jwmatthews requested changes
As of now, this is creating the logs directory 1 level higher than we want.

2024-08-07 15:15 UTC, jwmatthews commented on kai/kai_logging.py
> +        kai_project_directory = os.path.abspath(os.path.join(current_directory, ".."))
We need to change this and get rid of the "..", that was needed in past when we were basing the directory to the location of "__file__".

2024-08-07 15:56 UTC, brf153 commented
@jwmatthews made the required changes

2024-08-07 16:23 UTC, jwmatthews approved these changes
I tested both local dev and podman compose and verified logs are going to right location

2024-08-07 16:23 UTC, merged