:sparkles: Adding Analyzer and Maven Agents
konveyor/kai pull request #466
Opened 2024-11-01 18:22 UTC by shawn-hurley

also in this commit is the following:
* Remove xml line number parser and moved to lxml for xml
* Changed the way dep matches and overriding of deps was handled To not rely on line numbers
* Changed AgentResult to have defaults and updated a field from a list to a single value. This is because we should only work on a single file at a time, and we don't need more than one file in the agent.
* Added a test case for the AnalyzerAgent

2024-11-01 21:06 UTC, JonahSussman requested changes
One potential bug, spelling fix/nits. Otherwise looks good!

2024-11-01 21:06 UTC, JonahSussman commented on kai_solution_server/service/incident_store/incident_store.py
> +
This currently raises a `type[ValueError]` not a `ValueError`. I think you want to raise `ValueError()` instead.

2024-11-01 21:06 UTC, JonahSussman commented on requirements.txt
I'm just commenting for discussion, but is there a benefit of having this file anymore? All the requirements we have are in `pyproject.toml` now. 

@fabianvf @pranavgaikwad thoughts?

2024-11-04 16:59 UTC, closed without merging

2024-11-04 17:03 UTC, shawn-hurley commented on kai/reactive_codeplanner/agent/analyzer_fix/agent.py
> +        additional_details = ""
Both none and empty strings will give you false values, right? If that is the case, I think this is fine. Thoughts?